version: 2.1

parameters:
  nightly_build:
    type: boolean
    default: false
  weekly_build:
    type: boolean
    default: false

jobs:

  mac_build_and_test:
    macos:
      xcode: 15.2.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            xcodebuild -version
            xcrun --show-sdk-build-version
            swift --version
            xcodebuild test -scheme mlx-swift-Package -destination 'platform=OS X'

workflows:
  build_and_test:
    when:
      and:
        - not: << pipeline.parameters.nightly_build >>
        - not: << pipeline.parameters.weekly_build >>
    jobs:
      - mac_build_and_test

